# Configuration 
directories:
  input_dir: /u/home/c/clairewi/project-snaoz/FOF_project
  output_dir: /u/home/c/clairewi/project-snaoz/FOF_project
  code_dir: /u/home/c/clairewi/project-snaoz/FOF_Testing/process-fof

files: 
  newstars_sig0: './newstars_Sig0_25Mpc.dat'
  newstars_sig2: './newstars_Sig2_25Mpc.dat'

simulation_parameters:
  boxsize: 1776.0
  snapshots: [153,152,151,150]