# Configuration 
directories:
  input_dir: ./name_of_directory/
  output_dir: /name_of_directory/
  code_dir: /location/process-fof/

files: 
  newstars_sig0: './newstars_Sig0_25Mpc.dat'
  newstars_sig2: './newstars_Sig2_25Mpc.dat'

fof_algorithms:
  DMP-GS: 
    algorithm: 1 #1 to use this FOF, 0 to skip
    fof_params: 
      0Sigma: 1 #1 to use 0 sigma SV, 0 to skip
      2Sigma: 1 #1 to use 2 sigma SV, 0 to skip
  SGDMP:
    algorithm: 1 #1 to use this FOF, 0 to skip
    fof_params: 
      0Sigma: 1 #1 to use 0 sigma SV, 0 to skip
      2Sigma: 1 #1 to use 2 sigma SV, 0 to skip
  SP:
    algorithm: 1 #1 to use this FOF, 0 to skip
    fof_params: 
      0Sigma: 1 #1 to use 0 sigma SV, 0 to skip
      2Sigma: 1 #1 to use 2 sigma SV, 0 to skip
  SGP: 
    algorithm: 1 #1 to use this FOF, 0 to skip
    fof_params: 
      0Sigma: 1 #1 to use 0 sigma SV, 0 to skip
      2Sigma: 1 #1 to use 2 sigma SV, 0 to skip


simulation_parameters:
  boxsize: 1776.0
  snapshots: [153,152,151,150]