name: Sphinx build

on: push

jobs:
  sphinx-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Ensure all branches are fetched
      env: 
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    - name: Build HTML
      with:
        pre-build-command: "apt install -y pandoc"
      uses: ammaraskar/sphinx-action@0.4
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        SPHINXOPTS: "-v"  # Verbose Sphinx build output
        
    - name: Checkout gh-pages branch
      run: |
        git fetch origin gh-pages
        git checkout gh-pages

    - name: Clear old HTML files
      run: |
        rm -rf *  # This will remove all files in the gh-pages branch

    - name: Add clean commit
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Clear old files"

    - name: Push changes to gh-pages branch
      run: |
        git push origin gh-pages
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: html-docs
        path: docs/_build/html/
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      if: github.ref == 'refs/heads/main'
      env: 
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        publish_dir: docs/_build/html
        publish_branch: gh-pages
        force_orphan: true  # Force overwrite of gh-pages
        verbose: true
